version: "3"

services:
  web:
    container_name: app
    build: .
    image: yellowfolder
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    restart: always
    command: /app/node_modules/.bin/next dev
